/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnimekRouteImport } from './routes/animek'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchEpisodeIdRouteImport } from './routes/watch.$episodeId'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'

const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimekRoute = AnimekRouteImport.update({
  id: '/animek',
  path: '/animek',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchEpisodeIdRoute = WatchEpisodeIdRouteImport.update({
  id: '/watch/$episodeId',
  path: '/watch/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animek': typeof AnimekRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animek': typeof AnimekRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/animek': typeof AnimekRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/animek'
    | '/auth'
    | '/browse'
    | '/anime/$id'
    | '/watch/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/animek'
    | '/auth'
    | '/browse'
    | '/anime/$id'
    | '/watch/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/animek'
    | '/auth'
    | '/browse'
    | '/anime/$id'
    | '/watch/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnimekRoute: typeof AnimekRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  AnimeIdRoute: typeof AnimeIdRoute
  WatchEpisodeIdRoute: typeof WatchEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animek': {
      id: '/animek'
      path: '/animek'
      fullPath: '/animek'
      preLoaderRoute: typeof AnimekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$episodeId': {
      id: '/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof WatchEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnimekRoute: AnimekRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  AnimeIdRoute: AnimeIdRoute,
  WatchEpisodeIdRoute: WatchEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
